name: Commit CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ImeWlConverterCmd

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ./src/ImeWlConverterCmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "imewlconverter_Linux.tar.gz"
          path: ./publish

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ImeWlConverterCmd

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish-${{ matrix.arch }} ./src/ImeWlConverterCmd -a ${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "imewlconverter_macOS-${{ matrix.arch }}"
          path: ./publish-${{ matrix.arch }}

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "./src/IME WL Converter Win"

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish "./src/IME WL Converter Win"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: imewlconverter_Windows
          path: ./publish
